version: '2'
services:
  api-manager:
    build:
      context: ../
      dockerfile: pattern-0/api-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"
