version: '2'
services:
  apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-1/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  api-manager:
    build:
      context: ../
      dockerfile: pattern-0/api-manager/Dockerfile
    environment:
      - SLEEP=5
  nginx:
    build:
      context: ../
      dockerfile: pattern-0/nginx/Dockerfile
    environment:
      - SLEEP=60
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"
