version: '2'
services:
  apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-4/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: docker.wso2.com/svnrepo
  analytics:
    build:
      context: ../
      dockerfile: pattern-4/am-analytics/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9448:9444"
  traffic-manager:
    build:
      context: ../
      dockerfile: pattern-4/traffic-manager/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9447:9443"
  keymanager:
    build:
      context: ../
      dockerfile: pattern-4/keymanager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9443:9443"
  gateway-manager:
    build:
      context: ../
      dockerfile: pattern-4/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  gateway-worker:
    build:
      context: ../
      dockerfile: pattern-4/gateway-worker/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8280:8280"
    - "8243:8243"
  publisher-store:
    build:
      context: ../
      dockerfile: pattern-4/publisher-store/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"