[server]
hostname = "tm.am.wso2.com"
node_ip = "127.0.0.1"
server_role = "traffic-manager"

[transport.https.properties]
proxyPort = 443

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_SHARED_DB?autoReconnect=true&amp;useSSL=false&amp;allowPublicKeyRetrieval=true"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"


[database.apim_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_DB?autoReconnect=true&amp;useSSL=false&amp;allowPublicKeyRetrieval=true"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"


# key manager implementation
[apim.key_manager]
service_url = "https://api.am.wso2.com/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
type = "default"

[apim.oauth_config]
revoke_endpoint = "https://api.am.wso2.com/oauth2/revoke"
enable_token_encryption = false

[[apim.gateway.environment]]
name= "us-eeast-1"
type= "hybrid"
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
ws_endpoint= "ws://api.gw.wso2.com:9099"
https_endpoint = "https://api.gateway.wso2.com"

# Event Hub configurations
[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://api.am.wso2.com/services/"
event_listening_endpoints = ["tcp://apim-cp-1:5672", "tcp://apim-cp-2:5672"]


# Traffic Manager configurations
[apim.throttling]
event_duplicate_url = ["tcp://traffic-manager-1:5672"]
throttle_decision_endpoints = ["tcp://localhost:5672"]