version: '2'
services:
  apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-8/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: dockerhub.private.wso2.com/svnrepo
  am-analytics:
    build:
      context: ../
      dockerfile: pattern-8/am-analytics/Dockerfile
    environment:
      - SLEEP=5
  keymanager-tm-gw:
    build:
      context: ../
      dockerfile: pattern-8/keymanager-tm-gw/Dockerfile
    environment:
      - SLEEP=120
    links:
      - nginx:mgt.gateway.apim.wso2.com
      - nginx:publisher.apim.wso2.com
      - nginx:store.apim.wso2.com
      - nginx:keymanager-tm-gw.apim.wso2.com
      - nginx:analytics.apim.wso2.com
  gateway-manager:
    build:
      context: ../
      dockerfile: pattern-8/gateway-manager/Dockerfile
    environment:
      - SLEEP=60
    links:
      - nginx:mgt.gateway.apim.wso2.com
      - nginx:publisher.apim.wso2.com
      - nginx:store.apim.wso2.com
      - nginx:keymanager-tm-gw.apim.wso2.com
      - nginx:analytics.apim.wso2.com
  store:
    build:
      context: ../
      dockerfile: pattern-8/store/Dockerfile
    environment:
      - SLEEP=200
    links:
      - nginx:mgt.gateway.apim.wso2.com
      - nginx:publisher.apim.wso2.com
      - nginx:store.apim.wso2.com
      - nginx:keymanager-tm-gw.apim.wso2.com
      - nginx:analytics.apim.wso2.com
  publisher:
    build:
      context: ../
      dockerfile: pattern-8/publisher/Dockerfile
    environment:
      - SLEEP=200
    links:
      - nginx:mgt.gateway.apim.wso2.com
      - nginx:publisher.apim.wso2.com
      - nginx:store.apim.wso2.com
      - nginx:keymanager-tm-gw.apim.wso2.com
      - nginx:analytics.apim.wso2.com
  nginx:
    build:
      context: ../
      dockerfile: pattern-8/nginx/Dockerfile
    environment:
      - SLEEP=60
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"
      - "9444:9444"
      - "9764:9764"
