version: '2'
services:
  dbms:
    container_name: apim_rdbms
    build:
        context: ../
        dockerfile: pattern-2/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    container_name: svnrepo
    image: dockerhub.private.wso2.com/svnrepo
  am-analytics:
    container_name: am-analytics
    build:
      context: ../
      dockerfile: pattern-2/am-analytics/Dockerfile
    environment:
      - SLEEP=5
  keymanager:
    container_name: keymanager
    build:
      context: ../
      dockerfile: pattern-2/keymanager/Dockerfile
    environment:
      - SLEEP=5
    links:
      - nginx:apim-gateway-manager
      - nginx:apim-keymanager
      - nginx:apim-gateway-worker
      - nginx:apim-store
  gateway-manager:
    container_name: gateway-manager
    build:
      context: ../
      dockerfile: pattern-2/gateway-manager/Dockerfile
    environment:
      - SLEEP=50
    links:
      - nginx:apim-gateway-worker
      - nginx:apim-store
      - nginx:apim-publisher
      - nginx:apim-keymanager
  gateway-worker:
    container_name: gateway-worker
    build:
      context: ../
      dockerfile: pattern-2/gateway-worker/Dockerfile
    environment:
      - SLEEP=150
    links:
      - nginx:apim-gateway-manager
      - nginx:apim-store
      - nginx:apim-publisher
      - nginx:apim-keymanager
  store:
    container_name: store
    build:
      context: ../
      dockerfile: pattern-2/store/Dockerfile
    environment:
      - SLEEP=150
    links:
      - nginx:apim-gateway-manager
      - nginx:apim-gateway-worker
      - nginx:apim-publisher
      - nginx:apim-keymanager
  publisher:
    container_name: publisher
    build:
      context: ../
      dockerfile: pattern-2/publisher/Dockerfile
    environment:
      - SLEEP=150
    links:
      - nginx:apim-gateway-manager
      - nginx:apim-gateway-worker
      - nginx:apim-store
      - nginx:apim-keymanager
  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: pattern-2/nginx/Dockerfile
    environment:
      - SLEEP=60
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"
      - "9444:9444"
      - "9764:9764"
