version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/apim-pattern1-apim_rdbms:2.1.0
    build:
        context: ../
        dockerfile: pattern-1/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  api-manager:
    image: docker.wso2.com/apim-pattern1-api-manager:2.1.0
    build:
      context: ../
      dockerfile: pattern-1/api-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"
