version: '2'
services:
  apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-9/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: docker.wso2.com/svnrepo
  analytics:
    build:
      context: ../
      dockerfile: pattern-9/am-analytics/Dockerfile
    environment:
      - SLEEP=30
    ports:
    - "9448:9444"
  gateway-manager:
    build:
      context: ../
      dockerfile: pattern-9/gateway-manager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9444:9443"
  keymanager-tm-gw:
    build:
      context: ../
      dockerfile: pattern-9/keymanager-tm-gw/Dockerfile
    environment:
      - SLEEP=120
    ports:
    - "9443:9443"
    - "8280:8280"
    - "8243:8243"
  store:
    build:
      context: ../
      dockerfile: pattern-9/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  publisher:
    build:
      context: ../
      dockerfile: pattern-9/publisher/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"
  # nginx:
  #   build:
  #     context: ../
  #     dockerfile: pattern-9/nginx/Dockerfile
  #   environment:
  #     - SLEEP=60
  #   ports:
  #     - "443:9443"
  #     - "80:9763"