version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/swarm-apim-attern2-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-2/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  am-analytics:
    image: docker.wso2.com/swarm-apim-pattern2-wso2am-analytics:2.0.0
    build:
      context: ../
      dockerfile: pattern-2/am-analytics/Dockerfile
    environment:
        SLEEP: 5
    ports:
      - "9444:9444"
      - "9764:9764"
  api-manager:
    image: docker.wso2.com/swarm-apim-pattern2-wso2am:2.0.0
    build:
      context: ../
      dockerfile: pattern-2/api-manager/Dockerfile
    environment:
        SLEEP: 20
    ports:
      - "443:9443"
      - "8243:8243"
      - "8280:8280"
      - "80:9763"
