version: '2'
services:
  apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-7/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: docker.wso2.com/svnrepo
  analytics:
    build:
      context: ../
      dockerfile: pattern-7/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  traffic-manager:
    build:
      context: ../
      dockerfile: pattern-7/traffic-manager/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9447:9443"
  gateway-manager:
    build:
      context: ../
      dockerfile: pattern-7/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  gateway-worker-km:
    build:
      context: ../
      dockerfile: pattern-7/gateway-worker-km/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "9443:9443"
    - "8280:8280"
    - "8243:8243"
  store:
    build:
      context: ../
      dockerfile: pattern-7/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  publisher:
    build:
      context: ../
      dockerfile: pattern-7/publisher/Dockerfile
    environment:
      - SLEEP=240
    ports:
      - "9445:9443"
  # nginx:
  #   build:
  #     context: ../
  #     dockerfile: pattern-7/nginx/Dockerfile
  #   environment:
  #     - SLEEP=60
  #   ports:
  #     - "443:9443"
  #     - "80:9763"
