version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/swarm-apim-pattern7-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-7/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  api-manager:
    image: docker.wso2.com/swarm-apim-pattern7-wso2am:2.1.0
    build:
      context: ../
      dockerfile: pattern-7/api-manager/Dockerfile
    environment:
       SLEEP: 100
  is-key-manager:
    image: docker.wso2.com/swarm-apim-pattern7-wso2is-key-manager:2.1.0
    build:
      context: ../
      dockerfile: pattern-7/is-key-manager/Dockerfile
    environment:
      - SLEEP=120
