version: '2'
services:
  apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-7/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: dockerhub.private.wso2.com/svnrepo
  analytics:
    image: dockerhub.private.wso2.com/apim-pattern7-wso2am-analytics:2.0.0
    build:
      context: ../
      dockerfile: pattern-7/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  keymanager-tm:
    image: dockerhub.private.wso2.com/apim-pattern7-keymanager-tm:2.0.0
    build:
      context: ../
      dockerfile: pattern-7/keymanager-tm/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9443:9443"
  gateway-manager:
    image: dockerhub.private.wso2.com/apim-pattern7-gateway-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-7/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  gateway-worker:
    image: dockerhub.private.wso2.com/apim-pattern7-gateway-worker:2.0.0
    build:
      context: ../
      dockerfile: pattern-7/gateway-worker/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8280:8280"
    - "8243:8243"
  store:
    image: dockerhub.private.wso2.com/apim-pattern7-store:2.0.0
    build:
      context: ../
      dockerfile: pattern-7/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  publisher:
    image: dockerhub.private.wso2.com/apim-pattern7-publisher:2.0.0
    build:
      context: ../
      dockerfile: pattern-7/publisher/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"