version: '2.3'
services:
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5
  am-analytics:
    image: docker.wso2.com/wso2am-analytics:2.2.0
    ports:
      - "9444:9444"
      - "9764:9764"
      - "4041:4041"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9444/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./apim-analytics/repository/conf/datasources/analytics-datasources.xml:/home/wso2carbon/wso2am-analytics-2.2.0/repository/conf/datasources/analytics-datasources.xml
      - ./apim-analytics/repository/conf/datasources/stats-datasources.xml:/home/wso2carbon/wso2am-analytics-2.2.0/repository/conf/datasources/stats-datasources.xml
    links:
      - mysql
  api-manager:
    image: docker.wso2.com/wso2am:2.2.0
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 10
    depends_on:
      am-analytics:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./apim/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2am-2.2.0/repository/conf/datasources/master-datasources.xml
      - ./apim/repository/conf/api-manager.xml:/home/wso2carbon/wso2am-2.2.0/repository/conf/api-manager.xml
      - ./apim/repository/conf/carbon.xml:/home/wso2carbon/wso2am-2.2.0/repository/conf/carbon.xml
      - ./apim/repository/conf/tomcat/catalina-server.xml:/home/wso2carbon/wso2am-2.2.0/repository/conf/tomcat/catalina-server.xml
      - ./apim/bin/wso2server.sh:/home/wso2carbon/wso2am-2.2.0/bin/wso2server.sh
      - ./apim/repository/conf/on-premise-gateway.properties:/home/wso2carbon/wso2am-2.2.0/repository/conf/on-premise-gateway.properties
    ports:
      - "9763:9763"
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    links:
      - mysql
      - am-analytics
  api-manager-gateway:
    image: docker.wso2.com/wso2am-micro-gw:2.2.0
    depends_on:
      api-manager:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./micro-gw/repository/conf/api-manager.xml:/home/wso2carbon/wso2am-micro-gw-2.2.0/repository/conf/api-manager.xml
      - ./micro-gw/repository/conf/carbon.xml:/home/wso2carbon/wso2am-micro-gw-2.2.0/repository/conf/carbon.xml
      - ./micro-gw/repository/conf/jndi.properties:/home/wso2carbon/wso2am-micro-gw-2.2.0/repository/conf/jndi.properties
      - ./micro-gw/repository/conf/log4j.properties:/home/wso2carbon/wso2am-micro-gw-2.2.0/repository/conf/log4j.properties
      - ./micro-gw/repository/conf/on-premise-gateway.properties:/home/wso2carbon/wso2am-micro-gw-2.2.0/repository/conf/on-premise-gateway.properties
      - ./micro-gw/repository/conf/registry.xml:/home/wso2carbon/wso2am-micro-gw-2.2.0/repository/conf/registry.xml
      - ./micro-gw/bin/wso2server.sh:/home/wso2carbon/wso2am-micro-gw-2.2.0/bin/wso2server.sh
    ports:
      - "5673:5673"
      - "8244:8244"
    links:
      - mysql
      - am-analytics

